
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gulse
 */
public class siparisUygulamasi extends javax.swing.JFrame {
    
    Map<String,Integer> siparisler = new LinkedHashMap<String,Integer>(); //Sİparişleri kaydetmek için yapılan kısım eklenme sırasına göre kaydetsin istediğimiz için map ullanıyoruz
    
    
    
    
    /**
     * Creates new form siparisUygulamasi
     */
    public siparisUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        İskender = new javax.swing.JCheckBox();
        Beyti = new javax.swing.JCheckBox();
        Salata = new javax.swing.JCheckBox();
        Ayran = new javax.swing.JCheckBox();
        Siparis_Göster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiparisUygulamasi");

        jLabel1.setText("MENÜ");

        İskender.setText("İskender - 15TL");

        Beyti.setText("Beyti - 12TL");

        Salata.setText("Salata- 5 TL");

        Ayran.setText("Ayran - 2TL");

        Siparis_Göster.setText("Siparişleri Göster");
        Siparis_Göster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Siparis_GösterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ayran, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salata, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Beyti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(İskender, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(Siparis_Göster, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(İskender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Beyti, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ayran, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Siparis_Göster, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Siparis_Göster(){
        
        String message = " " ;
        int Tutar = 0;
        if (siparisler.isEmpty()) { // mapin boş olup olmadığını gösterecek.
            message = "Siparisiniz Bulunmamaktadir.";
        }else{
            message += "Siparisler\n";
            
            for (Map.Entry<String, Integer> entry : siparisler.entrySet()) {
               //for each döngüsü mapler de böyle yazılıyor.
               
                message += entry.getKey() + "\n";
                Tutar += entry.getValue();
                
            }
            message += "Toplam Tutar:" + Tutar;
        }
        JOptionPane.showMessageDialog(this, message); // ekrana yazdırma
        
    }
    
    
    private void Siparis_GösterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Siparis_GösterActionPerformed
       
        if (İskender.isSelected()) { // eğer iskender seçilmişse demek.
            
            siparisler.put("İskender", 15);
        }else {
            siparisler.remove("İskender");
        }
        
         if (Beyti.isSelected()) { // eğer beyti seçilmişse demek.
            
            siparisler.put("Beyti", 12);
        }else {
            siparisler.remove("Beyti");
        }
         
          if (Salata.isSelected()) { // eğer salata seçilmişse demek.
            
            siparisler.put("Salata", 5);
        }else {
            siparisler.remove("Salata");
        }
          
         if (Ayran.isSelected()) { // eğer Ayran seçilmişse demek.
            
            siparisler.put("Ayran", 2);
        }else {
            siparisler.remove("Ayran");
        }  
        
         Siparis_Göster();
         
        
        
        
        
    }//GEN-LAST:event_Siparis_GösterActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ayran;
    private javax.swing.JCheckBox Beyti;
    private javax.swing.JCheckBox Salata;
    private javax.swing.JButton Siparis_Göster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox İskender;
    // End of variables declaration//GEN-END:variables
}
